/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FreeGrowthAuditRouteImport } from './routes/free-growth-audit'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServiceWordpressRouteImport } from './routes/service.wordpress'
import { Route as ServiceWebDevRouteImport } from './routes/service.web-dev'
import { Route as ServiceWebAppRouteImport } from './routes/service.web-app'
import { Route as ServiceUiUxDesignRouteImport } from './routes/service.ui-ux-design'
import { Route as ServiceSocialMedRouteImport } from './routes/service.social-med'
import { Route as ServiceSeoRouteImport } from './routes/service.seo'
import { Route as ServicePpcRouteImport } from './routes/service.ppc'
import { Route as ServiceGraphicDesignRouteImport } from './routes/service.graphic-design'
import { Route as ServiceECommRouteImport } from './routes/service.e-comm'
import { Route as ServiceContentMarketingRouteImport } from './routes/service.content-marketing'
import { Route as ServiceBrandingRouteImport } from './routes/service.branding'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiGrowthAuditRouteImport } from './routes/api.growth-audit'
import { Route as AdminGrowthLeadsRouteImport } from './routes/admin.growth-leads'
import { Route as AdminContactLeadsRouteImport } from './routes/admin.contact-leads'
import { Route as AdminBlogPreviewRouteImport } from './routes/admin.blog-preview'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAddBlogRouteImport } from './routes/admin.add-blog'
import { Route as AdminAdLeadsRouteImport } from './routes/admin.ad-leads'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeGrowthAuditRoute = FreeGrowthAuditRouteImport.update({
  id: '/free-growth-audit',
  path: '/free-growth-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServiceWordpressRoute = ServiceWordpressRouteImport.update({
  id: '/service/wordpress',
  path: '/service/wordpress',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceWebDevRoute = ServiceWebDevRouteImport.update({
  id: '/service/web-dev',
  path: '/service/web-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceWebAppRoute = ServiceWebAppRouteImport.update({
  id: '/service/web-app',
  path: '/service/web-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceUiUxDesignRoute = ServiceUiUxDesignRouteImport.update({
  id: '/service/ui-ux-design',
  path: '/service/ui-ux-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSocialMedRoute = ServiceSocialMedRouteImport.update({
  id: '/service/social-med',
  path: '/service/social-med',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSeoRoute = ServiceSeoRouteImport.update({
  id: '/service/seo',
  path: '/service/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicePpcRoute = ServicePpcRouteImport.update({
  id: '/service/ppc',
  path: '/service/ppc',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceGraphicDesignRoute = ServiceGraphicDesignRouteImport.update({
  id: '/service/graphic-design',
  path: '/service/graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceECommRoute = ServiceECommRouteImport.update({
  id: '/service/e-comm',
  path: '/service/e-comm',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceContentMarketingRoute = ServiceContentMarketingRouteImport.update({
  id: '/service/content-marketing',
  path: '/service/content-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceBrandingRoute = ServiceBrandingRouteImport.update({
  id: '/service/branding',
  path: '/service/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiGrowthAuditRoute = ApiGrowthAuditRouteImport.update({
  id: '/api/growth-audit',
  path: '/api/growth-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGrowthLeadsRoute = AdminGrowthLeadsRouteImport.update({
  id: '/growth-leads',
  path: '/growth-leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactLeadsRoute = AdminContactLeadsRouteImport.update({
  id: '/contact-leads',
  path: '/contact-leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogPreviewRoute = AdminBlogPreviewRouteImport.update({
  id: '/blog-preview',
  path: '/blog-preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddBlogRoute = AdminAddBlogRouteImport.update({
  id: '/add-blog',
  path: '/add-blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdLeadsRoute = AdminAdLeadsRouteImport.update({
  id: '/ad-leads',
  path: '/ad-leads',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/free-growth-audit': typeof FreeGrowthAuditRoute
  '/industries': typeof IndustriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/ad-leads': typeof AdminAdLeadsRoute
  '/admin/add-blog': typeof AdminAddBlogRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog-preview': typeof AdminBlogPreviewRoute
  '/admin/contact-leads': typeof AdminContactLeadsRoute
  '/admin/growth-leads': typeof AdminGrowthLeadsRoute
  '/api/growth-audit': typeof ApiGrowthAuditRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/service/branding': typeof ServiceBrandingRoute
  '/service/content-marketing': typeof ServiceContentMarketingRoute
  '/service/e-comm': typeof ServiceECommRoute
  '/service/graphic-design': typeof ServiceGraphicDesignRoute
  '/service/ppc': typeof ServicePpcRoute
  '/service/seo': typeof ServiceSeoRoute
  '/service/social-med': typeof ServiceSocialMedRoute
  '/service/ui-ux-design': typeof ServiceUiUxDesignRoute
  '/service/web-app': typeof ServiceWebAppRoute
  '/service/web-dev': typeof ServiceWebDevRoute
  '/service/wordpress': typeof ServiceWordpressRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/free-growth-audit': typeof FreeGrowthAuditRoute
  '/industries': typeof IndustriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/ad-leads': typeof AdminAdLeadsRoute
  '/admin/add-blog': typeof AdminAddBlogRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog-preview': typeof AdminBlogPreviewRoute
  '/admin/contact-leads': typeof AdminContactLeadsRoute
  '/admin/growth-leads': typeof AdminGrowthLeadsRoute
  '/api/growth-audit': typeof ApiGrowthAuditRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/service/branding': typeof ServiceBrandingRoute
  '/service/content-marketing': typeof ServiceContentMarketingRoute
  '/service/e-comm': typeof ServiceECommRoute
  '/service/graphic-design': typeof ServiceGraphicDesignRoute
  '/service/ppc': typeof ServicePpcRoute
  '/service/seo': typeof ServiceSeoRoute
  '/service/social-med': typeof ServiceSocialMedRoute
  '/service/ui-ux-design': typeof ServiceUiUxDesignRoute
  '/service/web-app': typeof ServiceWebAppRoute
  '/service/web-dev': typeof ServiceWebDevRoute
  '/service/wordpress': typeof ServiceWordpressRoute
  '/blog': typeof BlogIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/free-growth-audit': typeof FreeGrowthAuditRoute
  '/industries': typeof IndustriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/ad-leads': typeof AdminAdLeadsRoute
  '/admin/add-blog': typeof AdminAddBlogRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog-preview': typeof AdminBlogPreviewRoute
  '/admin/contact-leads': typeof AdminContactLeadsRoute
  '/admin/growth-leads': typeof AdminGrowthLeadsRoute
  '/api/growth-audit': typeof ApiGrowthAuditRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/service/branding': typeof ServiceBrandingRoute
  '/service/content-marketing': typeof ServiceContentMarketingRoute
  '/service/e-comm': typeof ServiceECommRoute
  '/service/graphic-design': typeof ServiceGraphicDesignRoute
  '/service/ppc': typeof ServicePpcRoute
  '/service/seo': typeof ServiceSeoRoute
  '/service/social-med': typeof ServiceSocialMedRoute
  '/service/ui-ux-design': typeof ServiceUiUxDesignRoute
  '/service/web-app': typeof ServiceWebAppRoute
  '/service/web-dev': typeof ServiceWebDevRoute
  '/service/wordpress': typeof ServiceWordpressRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/free-growth-audit'
    | '/industries'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/admin/ad-leads'
    | '/admin/add-blog'
    | '/admin/blog'
    | '/admin/blog-preview'
    | '/admin/contact-leads'
    | '/admin/growth-leads'
    | '/api/growth-audit'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/service/branding'
    | '/service/content-marketing'
    | '/service/e-comm'
    | '/service/graphic-design'
    | '/service/ppc'
    | '/service/seo'
    | '/service/social-med'
    | '/service/ui-ux-design'
    | '/service/web-app'
    | '/service/web-dev'
    | '/service/wordpress'
    | '/blog/'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/cookie-policy'
    | '/free-growth-audit'
    | '/industries'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/admin/ad-leads'
    | '/admin/add-blog'
    | '/admin/blog'
    | '/admin/blog-preview'
    | '/admin/contact-leads'
    | '/admin/growth-leads'
    | '/api/growth-audit'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/service/branding'
    | '/service/content-marketing'
    | '/service/e-comm'
    | '/service/graphic-design'
    | '/service/ppc'
    | '/service/seo'
    | '/service/social-med'
    | '/service/ui-ux-design'
    | '/service/web-app'
    | '/service/web-dev'
    | '/service/wordpress'
    | '/blog'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/free-growth-audit'
    | '/industries'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/admin/ad-leads'
    | '/admin/add-blog'
    | '/admin/blog'
    | '/admin/blog-preview'
    | '/admin/contact-leads'
    | '/admin/growth-leads'
    | '/api/growth-audit'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/service/branding'
    | '/service/content-marketing'
    | '/service/e-comm'
    | '/service/graphic-design'
    | '/service/ppc'
    | '/service/seo'
    | '/service/social-med'
    | '/service/ui-ux-design'
    | '/service/web-app'
    | '/service/web-dev'
    | '/service/wordpress'
    | '/blog/'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  FreeGrowthAuditRoute: typeof FreeGrowthAuditRoute
  IndustriesRoute: typeof IndustriesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiGrowthAuditRoute: typeof ApiGrowthAuditRoute
  ServiceBrandingRoute: typeof ServiceBrandingRoute
  ServiceContentMarketingRoute: typeof ServiceContentMarketingRoute
  ServiceECommRoute: typeof ServiceECommRoute
  ServiceGraphicDesignRoute: typeof ServiceGraphicDesignRoute
  ServicePpcRoute: typeof ServicePpcRoute
  ServiceSeoRoute: typeof ServiceSeoRoute
  ServiceSocialMedRoute: typeof ServiceSocialMedRoute
  ServiceUiUxDesignRoute: typeof ServiceUiUxDesignRoute
  ServiceWebAppRoute: typeof ServiceWebAppRoute
  ServiceWebDevRoute: typeof ServiceWebDevRoute
  ServiceWordpressRoute: typeof ServiceWordpressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-growth-audit': {
      id: '/free-growth-audit'
      path: '/free-growth-audit'
      fullPath: '/free-growth-audit'
      preLoaderRoute: typeof FreeGrowthAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/service/wordpress': {
      id: '/service/wordpress'
      path: '/service/wordpress'
      fullPath: '/service/wordpress'
      preLoaderRoute: typeof ServiceWordpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/web-dev': {
      id: '/service/web-dev'
      path: '/service/web-dev'
      fullPath: '/service/web-dev'
      preLoaderRoute: typeof ServiceWebDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/web-app': {
      id: '/service/web-app'
      path: '/service/web-app'
      fullPath: '/service/web-app'
      preLoaderRoute: typeof ServiceWebAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/ui-ux-design': {
      id: '/service/ui-ux-design'
      path: '/service/ui-ux-design'
      fullPath: '/service/ui-ux-design'
      preLoaderRoute: typeof ServiceUiUxDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/social-med': {
      id: '/service/social-med'
      path: '/service/social-med'
      fullPath: '/service/social-med'
      preLoaderRoute: typeof ServiceSocialMedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/seo': {
      id: '/service/seo'
      path: '/service/seo'
      fullPath: '/service/seo'
      preLoaderRoute: typeof ServiceSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/ppc': {
      id: '/service/ppc'
      path: '/service/ppc'
      fullPath: '/service/ppc'
      preLoaderRoute: typeof ServicePpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/graphic-design': {
      id: '/service/graphic-design'
      path: '/service/graphic-design'
      fullPath: '/service/graphic-design'
      preLoaderRoute: typeof ServiceGraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/e-comm': {
      id: '/service/e-comm'
      path: '/service/e-comm'
      fullPath: '/service/e-comm'
      preLoaderRoute: typeof ServiceECommRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/content-marketing': {
      id: '/service/content-marketing'
      path: '/service/content-marketing'
      fullPath: '/service/content-marketing'
      preLoaderRoute: typeof ServiceContentMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/branding': {
      id: '/service/branding'
      path: '/service/branding'
      fullPath: '/service/branding'
      preLoaderRoute: typeof ServiceBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/growth-audit': {
      id: '/api/growth-audit'
      path: '/api/growth-audit'
      fullPath: '/api/growth-audit'
      preLoaderRoute: typeof ApiGrowthAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/growth-leads': {
      id: '/admin/growth-leads'
      path: '/growth-leads'
      fullPath: '/admin/growth-leads'
      preLoaderRoute: typeof AdminGrowthLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-leads': {
      id: '/admin/contact-leads'
      path: '/contact-leads'
      fullPath: '/admin/contact-leads'
      preLoaderRoute: typeof AdminContactLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-preview': {
      id: '/admin/blog-preview'
      path: '/blog-preview'
      fullPath: '/admin/blog-preview'
      preLoaderRoute: typeof AdminBlogPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add-blog': {
      id: '/admin/add-blog'
      path: '/add-blog'
      fullPath: '/admin/add-blog'
      preLoaderRoute: typeof AdminAddBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ad-leads': {
      id: '/admin/ad-leads'
      path: '/ad-leads'
      fullPath: '/admin/ad-leads'
      preLoaderRoute: typeof AdminAdLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdLeadsRoute: typeof AdminAdLeadsRoute
  AdminAddBlogRoute: typeof AdminAddBlogRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBlogPreviewRoute: typeof AdminBlogPreviewRoute
  AdminContactLeadsRoute: typeof AdminContactLeadsRoute
  AdminGrowthLeadsRoute: typeof AdminGrowthLeadsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdLeadsRoute: AdminAdLeadsRoute,
  AdminAddBlogRoute: AdminAddBlogRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBlogPreviewRoute: AdminBlogPreviewRoute,
  AdminContactLeadsRoute: AdminContactLeadsRoute,
  AdminGrowthLeadsRoute: AdminGrowthLeadsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  FreeGrowthAuditRoute: FreeGrowthAuditRoute,
  IndustriesRoute: IndustriesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiGrowthAuditRoute: ApiGrowthAuditRoute,
  ServiceBrandingRoute: ServiceBrandingRoute,
  ServiceContentMarketingRoute: ServiceContentMarketingRoute,
  ServiceECommRoute: ServiceECommRoute,
  ServiceGraphicDesignRoute: ServiceGraphicDesignRoute,
  ServicePpcRoute: ServicePpcRoute,
  ServiceSeoRoute: ServiceSeoRoute,
  ServiceSocialMedRoute: ServiceSocialMedRoute,
  ServiceUiUxDesignRoute: ServiceUiUxDesignRoute,
  ServiceWebAppRoute: ServiceWebAppRoute,
  ServiceWebDevRoute: ServiceWebDevRoute,
  ServiceWordpressRoute: ServiceWordpressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
